CREATE DATABASE IF NOT EXISTS Atividade2;
USE Atividade2;

CREATE TABLE IF NOT EXISTS EMPRESA (
ID_EMPRESA INT(11) PRIMARY KEY,
CNPJ VARCHAR(20) NOT NULL,
NOME_FANTASIA VARCHAR(50) NOT NULL,
ENDEREÇO VARCHAR(200) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
EMPRESA_ID INT NOT NULL,
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID_EMPRESA));

CREATE TABLE IF NOT EXISTS RESULTADO_EXAME (
ID_TIPO_RESULTADO_EXAME INT(11) PRIMARY KEY,
TIPO VARCHAR(30) NOT NULL);

CREATE TABLE IF NOT EXISTS TIPO_EXAME (
ID_TIPO_EXAME INT(11) PRIMARY KEY,
TIPO VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS EXAME (
ID_EXAME INT(11) PRIMARY KEY,
ESPECIALIDADE VARCHAR(50) NOT NULL,
DATA_REALIZAÇÃO DATE,
TIPO_EXAME_ID_TIPO_EXAME INT NOT NULL,
RESULTADO_EXAME_ID_TIPO_RESULTADO_EXAME INT NOT NULL,
FOREIGN KEY (TIPO_EXAME_ID_TIPO_EXAME) REFERENCES RESULTADO_EXAME(ID_TIPO_RESULTADO_EXAME),
FOREIGN KEY (ID_TIPO_EXAME) REFERENCES TIPO_EXAME(ID_TIPO_EXAME));

CREATE TABLE IF NOT EXISTS MÉDICO (
ID_MÉDICO INT(11) PRIMARY KEY,
CRM INT(11) NOT NULL,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(20) NOT NULL,
ESPECIALIDADE VARCHAR(50) NOT NULL,
DATA_NASCIMENTO DATE,
TELEFONE VARCHAR(20));

CREATE TABLE IF NOT EXISTS ATESTADO (
ID_ATESTADO INT(11) PRIMARY KEY,
RESULTADOS_RISCOS VARCHAR(100) NOT NULL,
RESULTADO VARCHAR(100) NOT NULL,
OBSERVAÇÕES VARCHAR(300) NOT NULL,
MÉDICO_ID INT NOT NULL,
FOREIGN KEY (MÉDICO_ID) REFERENCES MÉDICO(ID_MÉDICO));

CREATE TABLE IF NOT EXISTS CARGO (
ID_CARGO INT(11) PRIMARY KEY,
NOME VARCHAR(45) NOT NULL);

CREATE TABLE IF NOT EXISTS FUNCIONÁRIOS (
ID_FUNCIONÁRIO INT(11) PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(20) NOT NULL,
DATA_NASCIMENTO date,
ENDEREÇO VARCHAR(200) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
CARGO_ID_CARGO INT NOT NULL,
EMPRESA_ID_EMPRESA INT NOT NULL,
CONSTRAINT FOREIGN KEY (CARGO_ID_CARGO) REFERENCES CARGO(ID_CARGO),
CONSTRAINT FOREIGN KEY (EMPRESA_ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA));

CREATE TABLE IF NOT EXISTS RISCOS_OCUPACIONAIS (
ID_RISCOS INT(11) PRIMARY KEY,
NOME VARCHAR(45) NOT NULL);

CREATE TABLE IF NOT EXISTS CARGO_RISCOS_OCUPACIONAIS (
CARGO_ID_CARGO INT NOT NULL,
RISCOS_OCUPACIONAIS_ID_RISCOS INT NOT NULL,
FOREIGN KEY (CARGO_ID_CARGO) REFERENCES CARGO(ID_CARGO),
FOREIGN KEY (RISCOS_OCUPACIONAIS_ID_RISCOS) REFERENCES RISCOS_OCUPACIONAIS(ID_RISCOS));
